# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 23:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160208_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=32), blank=True, help_text='Comma separated list of tags', null=True, size=10),
        ),
    ]
