# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 01:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160208_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, db_index=True, related_name='posts', to='blog.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=32), blank=True, db_index=True, help_text='Comma separated list of tags', null=True, size=10),
        ),
    ]
