# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 02:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_auto_20160208_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPost',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('modified_at', models.DateTimeField(blank=True, editable=False)),
                ('cover_image', models.TextField(blank=True, max_length=100, null=True)),
                ('title', models.TextField(help_text='Title of post')),
                ('content', froala_editor.fields.FroalaField()),
                ('excerpt', models.TextField(blank=True, help_text='Custom intro or short version of the content', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Private'), (2, 'Published')], default=0)),
                ('comments_allowed', models.BooleanField(default=True, help_text='If comments are allowed')),
                ('removed', models.BooleanField(default=False, help_text='Temporarily remove post')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.SlugField(max_length=32), blank=True, db_index=True, help_text='Comma separated list of tags', null=True, size=10)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical post',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
