# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20160222_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='name',
        ),
        migrations.AlterField(
            model_name='historicalpost',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Save As Draft'), (1, 'Publish within IIT'), (2, 'Request Pending'), (3, 'Publish to Public')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Save As Draft'), (1, 'Publish within IIT'), (2, 'Request Pending'), (3, 'Publish to Public')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
