# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20160302_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
